### ISSUE TITLE
What is the point of having yet another debugging levels system?

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/moodle-block_intuitel#4]
Why is there a separate system of `block_intuitel_debug_level`? Would not relying on the Moodle's in-built `debugging()` function be more convenient?

**Comment by juacas** [comment]
It controls the debugging of a set of functionality that is not directly related to Moodle but to the communication protocol and the tutorship behaviour of INTUITEL system (protocol messages, tracing of students behaviour, etc). It logs the messages in a specific log file which only aim is to debug that protocol messages.
Moreover, under some circumstances it could be necessary to enable such characteristic in a production setup without pushing all the LMS into debug mode.

**Comment by mudrd8mz** [comment]
> it could be necessary to enable such characteristic in a production setup without pushing all the LMS into debug mode

Right, that makes perfect sense. Thanks!
