### ISSUE TITLE
Unexpected names of global scope functions

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/moodle-block_intuitel#6]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions

**Comment by juacas** [comment]
All functions in locallib.php has now the prefix 'intuitel_' to avoid name collisions.

**Comment by mudrd8mz** [comment]
I don't think that's correct. The `intuitel_` prefix would be valid for the activity module called `mod_intuitel`. You plugin is a block so valid prefix is `block_intuitel_`.

I just realized that the dev docs at https://docs.moodle.org/dev/Coding_style#Functions_and_Methods were not quite clear about it so I improved that section. Sorry for the confusion.

**Comment by juacas** [comment]
OK. Function names are going to be very long but I will change them a.s.a.p.

**Comment by mudrd8mz** [comment]
Yeah, I am aware of that. For that reason, it may be more convenient to wrap them as (possibly static) methods of a helper class. But the length itself is not an issue as long as the names are readable and intuitive / self-descriptive.
